name : kk funda

on: push

jobs:
  myfiles:
    runs-on : ubuntu-latest

    steps:
      - name : Create a file
        run : echo " File created and its Safe " > mytext.txt

      - name : Display the File
        run : cat mytext.txt
  
      - name : Display the date
        run : date
      - name : Display the Directory content
        run : ls -lrth

      - name : Display present path
        run : pwd

