name : Testing work flow Dispatch

on : workflow_dispatch 

jobs:
  Testing_flow:
    runs-on : ubuntu-latest

    steps:
      - name : Test the flow
        run : echo " Run complete "

